@startuml
SeekBar -> ProgressBar: onAttachedToWindow
SeekBar -> AbsSeekBar: onTouchEvent
AbsSeekBar -> AbsSeekBar: trackTouchEvent
AbsSeekBar -> ProgressBar: setProgressInternal
ProgressBar -> ProgressBar: refreshProgress
ProgressBar -> ProgressBar: doRefreshProgress
ProgressBar -> ProgressBar: onProgressRefresh
ProgressBar -> SeekBar: onProgressRefresh

@enduml